#!/usr/bin/env bash
set -e

INPUT_DOCKERFILE=${INPUT_DOCKERFILE:-Dockerfile}
INPUT_TAG=${INPUT_TAG:-$GITHUB_SHA}
INPUT_REPOSITORY=${INPUT_REPOSITORY}

echo "Building Docker image ${INPUT_REPOSITORY}/${INPUT_IMAGE}:${INPUT_TAG} from ${INPUT_GITHUB_REPOSITORY} on ${INPUT_BRANCH} and using context ${INPUT_FOLDER} ; and pushing it to ${INPUT_REGISTRY} Azure Container Registry"

az login --service-principal -u $SERVICE_PRINCIPAL -p $SERVICE_PRINCIPAL_PASSWORD --tenant $TENANT

az acr build -r ${INPUT_REGISTRY} -f ${INPUT_DOCKERFILE} -t ${INPUT_REPOSITORY}/${INPUT_IMAGE}:${INPUT_TAG} ${INPUT_GITHUB_REPOSITORY}#${INPUT_BRANCH}:${INPUT_FOLDER}
